"""Central configuration and tunable knobs.

Keeping the recommendation weights and decision thresholds in one place makes the
system auditable and makes the evals meaningful — every magic number that drives a
Buy/Sell/Hold call lives here, not scattered across the agents.
"""

from __future__ import annotations

import os


# --- Data source --------------------------------------------------------------
# "auto"    -> try live yfinance, transparently fall back to bundled fixtures
# "live"    -> live only (raise if unavailable)
# "fixture" -> bundled fixtures only (deterministic, offline)
DATA_SOURCE = os.environ.get("TICKER_DATA_SOURCE", "auto").lower()


# --- LLM (optional) -----------------------------------------------------------
LLM_MODEL = os.environ.get("TICKER_LLM_MODEL", "claude-opus-4-8")
HAS_API_KEY = bool(os.environ.get("ANTHROPIC_API_KEY"))


# --- Recommendation engine ----------------------------------------------------
# How much each specialist agent's score contributes to the composite score.
# These sum to 1.0. Tweak here to re-balance the committee.
AGENT_WEIGHTS: dict[str, float] = {
    "technical": 0.30,
    "fundamental": 0.30,
    "sentiment": 0.20,
    "risk": 0.20,
}

# Composite score (range [-1, +1]) -> recommendation.
BUY_THRESHOLD = 0.20
SELL_THRESHOLD = -0.20

# Guardrail: if aggregate data confidence is below this, we refuse to issue a
# directional call and force HOLD ("insufficient data to take a position").
MIN_CONFIDENCE_FOR_DIRECTIONAL_CALL = 0.35

# Mandatory compliance text appended to every report.
DISCLAIMER = (
    "This report is generated by an automated research system for educational and "
    "informational purposes only. It is not investment advice, and not a "
    "recommendation, offer, or solicitation to buy or sell any security. Markets are "
    "risky; past performance does not guarantee future results. Always do your own "
    "research and consult a licensed financial advisor before investing."
)
