"""Central configuration and tunable knobs.

Keeping the recommendation weights and decision thresholds in one place makes the
system auditable and makes the evals meaningful — every magic number that drives a
Buy/Sell/Hold call lives here, not scattered across the agents.
"""

from __future__ import annotations

import os


# --- Data source --------------------------------------------------------------
# "auto"    -> try live yfinance, transparently fall back to bundled fixtures
# "live"    -> live only (raise if unavailable)
# "fixture" -> bundled fixtures only (deterministic, offline)
DATA_SOURCE = os.environ.get("TICKER_DATA_SOURCE", "auto").lower()


# --- LLM (optional) -----------------------------------------------------------
# --- v2 ---
# The LLM layer was migrated from Anthropic Claude to OpenAI. Everything that used
# to read ANTHROPIC_API_KEY / TICKER_LLM_MODEL now reads OpenAI settings below.
# The deterministic core does NOT depend on any of this — it is all optional.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
HAS_API_KEY = bool(OPENAI_API_KEY)

# Cost-aware two-tier router. We default every call to the cheap model and only
# escalate to the strong model when the agent's reflection fails or confidence is
# too low (see app/reasoning/agent.py). Both are env-overridable.
LLM_TIER_CHEAP = os.environ.get("TICKER_LLM_TIER_CHEAP", "gpt-4o-mini")
LLM_TIER_STRONG = os.environ.get("TICKER_LLM_TIER_STRONG", "gpt-4o")

# Price table in USD per 1K tokens (input, output). Used by the CostMeter to turn
# token usage into dollars. Tunable here so pricing changes never touch code.
# Values reflect public OpenAI list prices at time of writing; adjust as needed.
MODEL_PRICES: dict[str, tuple[float, float]] = {
    "gpt-4o-mini": (0.00015, 0.00060),
    "gpt-4o": (0.00250, 0.01000),
}

# Optional hard ceiling on how much one /api/reason run may spend. 0 disables the
# cap. When exceeded the run aborts cleanly (the deterministic report is unaffected).
REASONING_BUDGET_USD = float(os.environ.get("TICKER_REASONING_BUDGET_USD", "0.05"))

# Agentic loop bounds and the reflection gate that triggers cheap->strong escalation.
MAX_TOOL_STEPS = int(os.environ.get("TICKER_MAX_TOOL_STEPS", "8"))
MAX_ESCALATIONS = int(os.environ.get("TICKER_MAX_ESCALATIONS", "1"))
REFLECTION_CONFIDENCE_FLOOR = float(os.environ.get("TICKER_REFLECTION_FLOOR", "0.55"))
# --- end v2 ---


# --- Recommendation engine ----------------------------------------------------
# How much each specialist agent's score contributes to the composite score.
# These sum to 1.0. Tweak here to re-balance the committee.
AGENT_WEIGHTS: dict[str, float] = {
    "technical": 0.30,
    "fundamental": 0.30,
    "sentiment": 0.20,
    "risk": 0.20,
}

# Composite score (range [-1, +1]) -> recommendation.
BUY_THRESHOLD = 0.20
SELL_THRESHOLD = -0.20

# Guardrail: if aggregate data confidence is below this, we refuse to issue a
# directional call and force HOLD ("insufficient data to take a position").
MIN_CONFIDENCE_FOR_DIRECTIONAL_CALL = 0.35

# Mandatory compliance text appended to every report.
DISCLAIMER = (
    "This report is generated by an automated research system for educational and "
    "informational purposes only. It is not investment advice, and not a "
    "recommendation, offer, or solicitation to buy or sell any security. Markets are "
    "risky; past performance does not guarantee future results. Always do your own "
    "research and consult a licensed financial advisor before investing."
)
